# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/engin/Documents/Logic_Design_Laboratory/final_project/flappyQ2/flappyQ2.srcs/sources_1/ip/blk_mem_gen_num_9/blk_mem_gen_num_9.xci
# IP: The module: 'blk_mem_gen_num_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/engin/Documents/Logic_Design_Laboratory/final_project/flappyQ2/flappyQ2.srcs/sources_1/ip/blk_mem_gen_num_9/blk_mem_gen_num_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_num_9'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/engin/Documents/Logic_Design_Laboratory/final_project/flappyQ2/flappyQ2.srcs/sources_1/ip/blk_mem_gen_num_9/blk_mem_gen_num_9.xci
# IP: The module: 'blk_mem_gen_num_9' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/engin/Documents/Logic_Design_Laboratory/final_project/flappyQ2/flappyQ2.srcs/sources_1/ip/blk_mem_gen_num_9/blk_mem_gen_num_9_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_num_9'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
